---
title: "Mara Braddy"
format: gfm
editor: visual
---

::: {style="text-align:center"}
<strong>Contact Info</strong>
:::

::: {style="text-align:center"}
marabraddy12\@gmail.com, 435-890-6195
:::

## Education

-   Utah State University, *Bachelor of Science in Biology*, Graduated 2019

-   Cornell University, *MPS in Natural Resources & the Environment*, 2026

## Skills

1.  Writing/Editing
2.  Teaching
3.  Gardening
4.  RStudio
5.  Git and GitHub

## Experience

-   Project Assistant, *Alumni Affiars & Development*, Cornell University

-   Student Services Associate, *College of Agriculture & Life Sciences*, Cornell University

-   IRB Assistant, *Research Services*, Cornell University

-   Nature Preschool Teacher, *Stokes Nature Center*

-   Fundraising Assistant, *Stokes Nature Center*

## Volunteer

-   Circus Teacher, Circus Culture

-   Farm Volunteer and Communications Intern, Groundswell

-   Board Member, Sustainable Finger Lakes


::: {.columns}
::: {.column width="60%"}
Master of Professional Studies, Natural Resources and the Environment
:::
::: {.column width="40%" style="text-align:right"}
Cornell University
:::
::::
:::: {.columns style="margin-top:0.25rem"}
::: {.column width="60%"}
:::
::: {.column width="40%" style="text-align:right"}
Expected Graduation: May 2026
:::
::::
